package jsonc

import (
	"encoding/json"
	"fmt"
	"math"
	"strings"
	"testing"
	"unicode/utf8"

	"pgregory.net/rapid"
)

// ============================================================================
// SECTION 1: Parse correctness properties
// ============================================================================

// propParseValidJSON asserts that Parse does NOT return an error for any
// structurally valid JSON generated by our generators.
func TestProperty_ParseValidJSON(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genJSONWithoutComments.Draw(t, "jsonInput")
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error for valid JSON %q: %v", input, err)
		}
		if doc == nil {
			t.Fatal("Parse returned nil Document with no error")
			return
		}
		if doc.Kind != KindDocument {
			t.Fatalf("Expected KindDocument, got %s", doc.Kind)
		}
	})
}

// propParseValidJSONC asserts Parse succeeds for JSONC with comments.
func TestProperty_ParseValidJSONC(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genFullJSONC(t)
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error for JSONC %q: %v", input, err)
		}
		if doc == nil {
			t.Fatal("Parse returned nil Document")
		}
	})
}

// propParseNumberValues asserts numbers parse correctly and the raw text matches.
func TestProperty_ParseNumberValues(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genNumbersString.Draw(t, "num")
		if input == "" {
			return
		}
		// Wrap in an array to test as a value
		src := "[" + input + "]"
		doc, err := Parse([]byte(src))
		if err != nil {
			t.Fatalf("Parse error for number %q: %v", input, err)
		}
		arr := doc.FirstChild()
		if arr == nil || arr.Kind != KindArray {
			t.Fatalf("Expected array, got %v", arr)
		}
		// The number node should be the first value element
		for _, c := range arr.Children {
			if c.IsValue() {
				if c.Kind != KindNumber {
					t.Fatalf("Expected Number node, got %s for value %q", c.Kind, c.Value)
				}
				// Verify it parses as a valid JSON number
				var f float64
				if err := json.Unmarshal([]byte(c.Value), &f); err != nil {
					continue
				}
				if math.IsInf(f, 0) || math.IsNaN(f) {
					t.Fatalf("Number %q produced Inf/NaN", c.Value)
				}
				return
			}
		}
		t.Fatalf("No value node found for number %q", input)
	})
}

// propParseStringValues asserts strings parse correctly with proper content.
func TestProperty_ParseStringValues(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		s := genJSONString.Draw(t, "str")
		src := "[" + s + "]"
		doc, err := Parse([]byte(src))
		if err != nil {
			t.Fatalf("Parse error for string %q: %v", s, err)
		}
		arr := doc.FirstChild()
		if arr == nil || arr.Kind != KindArray {
			t.Fatalf("Expected array root, got %v", arr)
		}
		found := false
		for _, c := range arr.Children {
			if c.Kind == KindString {
				found = true
				// The raw text should include the surrounding quotes
				if !strings.HasPrefix(c.Value, "\"") || !strings.HasSuffix(c.Value, "\"") {
					t.Fatalf("String value %q should have surrounding quotes", c.Value)
				}
				break
			}
		}
		if !found {
			t.Fatalf("No String node found for %q", s)
		}
	})
}

// propParseBooleanValues asserts true/false are correctly identified.
func TestProperty_ParseBooleanValues(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := rapid.SampledFrom([]string{"true", "false", " null ", " true ", "false "}).Draw(t, "boolInput")
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error for %q: %v", input, err)
		}
		// Should at least find some boolean nodes or the value
		bools := doc.FindAll(KindBoolean)
		if strings.Contains(input, "true") || strings.Contains(input, "false") {
			if len(bools) == 0 && !strings.Contains(input, "null") {
				t.Fatalf("No Boolean node found for %q", input)
			}
		}
	})
}

// propParseNull asserts null is correctly identified.
func TestProperty_ParseNull(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		// Must wrap in array for proper parsing since null alone is valid JSON
		input := rapid.SampledFrom([]string{
			"[null]",
			"[ null ]",
			"[null, null]",
			"{\"a\": null}",
		}).Draw(t, "nullInput")

		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error for %q: %v", input, err)
		}
		nulls := doc.FindAll(KindNull)
		if len(nulls) == 0 {
			t.Fatalf("No Null nodes found for %q", input)
		}
		for _, n := range nulls {
			if n.Value != "null" {
				t.Fatalf("Null node has value %q, expected %q", n.Value, "null")
			}
		}
	})
}

// ============================================================================
// SECTION 2: Container value properties
// ============================================================================

// propParseObjectStructure verifies object parsing preserves member structure.
func TestProperty_ParseObjectStructure(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genObject(t)
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error for object %q: %v", input, err)
		}
		obj := doc.FirstChild()
		if obj == nil {
			t.Fatalf("No children in document for %q", input)
			return
		}
		if obj.Kind != KindObject {
			t.Fatalf("Expected Object, got %s", obj.Kind)
		}

		// Verify brace positions
		hasLBrace, hasRBrace := false, false
		for _, c := range obj.Children {
			if c.Kind == KindLBrace {
				hasLBrace = true
			}
			if c.Kind == KindRBrace {
				hasRBrace = true
			}
		}
		if !hasLBrace {
			t.Fatal("Object missing { brace node")
		}
		if !hasRBrace {
			t.Fatal("Object missing } brace node")
		}

		// Verify members have keys and values
		for _, m := range obj.Members() {
			key := m.KeyNode()
			val := m.ValueNode()
			if key == nil {
				t.Fatal("Member without key node")
				return
			}
			if val == nil {
				t.Fatal("Member without value node")
			}
			if !strings.HasPrefix(key.Value, `"`) {
				t.Fatalf("Key node value %q should be quoted", key.Value)
			}
		}
	})
}

// propParseArrayStructure verifies array parsing preserves element structure.
func TestProperty_ParseArrayStructure(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genArray(t)
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error for array %q: %v", input, err)
		}
		arr := doc.FirstChild()
		if arr == nil {
			t.Fatalf("No children in document for %q", input)
			return
		}
		if arr.Kind != KindArray {
			t.Fatalf("Expected Array, got %s", arr.Kind)
		}

		hasLBracket, hasRBracket := false, false
		for _, c := range arr.Children {
			if c.Kind == KindLBracket {
				hasLBracket = true
			}
			if c.Kind == KindRBracket {
				hasRBracket = true
			}
		}
		if !hasLBracket {
			t.Fatal("Array missing [ bracket")
		}
		if !hasRBracket {
			t.Fatal("Array missing ] bracket")
		}
	})
}

// propParseNestedStructures verifies deeply nested structures work.
func TestProperty_ParseNestedStructures(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		// Build a complex nested structure manually
		nested := `{"a": [1, {"b": {"c": [[],[1,2,3],{"d": null}]}}, {"e": true, "f": false}]}`
		doc, err := Parse([]byte(nested))
		if err != nil {
			t.Fatalf("Parse error for nested JSON: %v", err)
		}
		// Verify top-level object
		obj := doc.FirstChild()
		if obj == nil || obj.Kind != KindObject {
			t.Fatal("Expected top-level Object")
		}
		members := obj.Members()
		if len(members) != 1 {
			t.Fatalf("Expected 1 member at top level, got %d", len(members))
		}
		// Check key "a"
		if members[0].KeyNode() == nil {
			t.Fatal("Member missing key node")
		}
	})
}

// ============================================================================
// SECTION 3: Comment preservation properties
// ============================================================================

// propLineCommentPreserved asserts line comments (//) are in the CST.
func TestProperty_LineCommentPreserved(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genLineComment.Draw(t, "comment")
		// Wrap so it's valid JSONC
		src := "[" + input + "\n]"
		doc, err := Parse([]byte(src))
		if err != nil {
			t.Fatalf("Parse error for line comment %q: %v", src, err)
		}
		comments := doc.FindAllComments()
		if len(comments) == 0 {
			t.Fatalf("No comment nodes found for %q", src)
		}
		// The comment text should start with //
		for _, c := range comments {
			if !strings.HasPrefix(c.Value, "//") {
				t.Fatalf("Line comment value %q doesn't start with //", c.Value)
			}
			if c.CommentStyle != CommentLine {
				t.Fatalf("Expected CommentLine style, got %d", c.CommentStyle)
			}
		}
	})
}

// propBlockCommentPreserved asserts block comments (/* */) are in the CST.
func TestProperty_BlockCommentPreserved(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genBlockComment.Draw(t, "comment")
		src := "[" + input + "]"
		doc, err := Parse([]byte(src))
		if err != nil {
			t.Fatalf("Parse error for block comment %q: %v", src, err)
		}
		comments := doc.FindAllComments()
		if len(comments) == 0 {
			t.Fatalf("No comment nodes found for %q", src)
		}
		for _, c := range comments {
			if c.CommentStyle != CommentBlock {
				t.Fatalf("Expected CommentBlock style, got %d", c.CommentStyle)
			}
			if !strings.HasPrefix(c.Value, "/*") {
				t.Fatalf("Block comment value %q doesn't start with /*", c.Value)
			}
			if !strings.HasSuffix(c.Value, "*/") {
				t.Fatalf("Block comment value %q doesn't end with */", c.Value)
			}
		}
	})
}

// propMixedComments asserts both comment types appear in the CST.
func TestProperty_MixedComments(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		src := "[\n  // line comment\n  /* block comment */\n  // another line\n]"
		doc, err := Parse([]byte(src))
		if err != nil {
			t.Fatalf("Parse error for mixed comments: %v", err)
		}
		comments := doc.FindAllComments()
		if len(comments) < 2 {
			t.Fatalf("Expected at least 2 comments, got %d: %v", len(comments), comments)
		}
		lineCount, blockCount := 0, 0
		for _, c := range comments {
			switch c.CommentStyle {
			case CommentLine:
				lineCount++
			case CommentBlock:
				blockCount++
			}
		}
		if lineCount == 0 {
			t.Fatal("No line comments found")
		}
		if blockCount == 0 {
			t.Fatal("No block comments found")
		}
	})
}

// propCommentBodyExtracted asserts the comment body (without delimiters) is stored.
func TestProperty_CommentBodyExtracted(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		letter := rapid.Custom(func(t *rapid.T) rune {
			return []rune("abcdefghijklmnopqrstuvwxyz ")[rapid.IntRange(0, 26).Draw(t, "ci")]
		})
		line := rapid.StringOf(letter).Draw(t, "lineBody")
		block := rapid.StringOf(letter).Draw(t, "blockBody")

		src := fmt.Sprintf("[//%s\n /* %s */]", line, block)
		doc, err := Parse([]byte(src))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		for _, c := range doc.FindAllComments() {
			if c.CommentStyle == CommentLine && c.CommentBody != "" {
				// Line comment body - could have leading space
				if !strings.Contains(c.CommentBody, strings.TrimSpace(line)) {
					// Just check it's not empty and is meaningful
					if c.CommentBody == "" {
						t.Fatalf("Line comment body should not be empty for %q", c.Value)
					}
				}
			}
		}
	})
}

// propCommentPreservedInJSONC asserts that comments in various positions
// (before object, after value, between members) are preserved.
func TestProperty_CommentPreservedInJSONC(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		src := "{\n  // before first\n  \"a\": 1, // after value\n  /* between */\n  \"b\": 2\n}"
		doc, err := Parse([]byte(src))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		comments := doc.FindAllComments()
		if len(comments) < 3 {
			t.Fatalf("Expected at least 3 comments, got %d", len(comments))
		}
	})
}

// ============================================================================
// SECTION 4: Position tracking properties
// ============================================================================

// propPositionsAreMonotonic asserts that for each node, start <= end
// and child positions are within parent positions.
func TestProperty_PositionsAreMonotonic(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genFullJSONC(t)
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		errs := validatePositions(doc)
		if len(errs) > 0 {
			t.Fatalf("Position violations:\n%s", strings.Join(errs, "\n"))
		}
	})
}

func validatePositions(n *Node) []string {
	var errs []string
	if n == nil {
		return nil
	}
	if n.Start.Offset > n.End.Offset {
		errs = append(errs, fmt.Sprintf("Node %s: start %d > end %d", n.Kind, n.Start.Offset, n.End.Offset))
	}
	for _, c := range n.Children {
		if c.Start.Offset < n.Start.Offset {
			errs = append(errs, fmt.Sprintf(
				"Child %s start %d < parent %s start %d",
				c.Kind, c.Start.Offset, n.Kind, n.Start.Offset,
			))
		}
		if c.End.Offset > n.End.Offset {
			errs = append(errs, fmt.Sprintf("Child %s end %d > parent %s end %d", c.Kind, c.End.Offset, n.Kind, n.End.Offset))
		}
		errs = append(errs, validatePositions(c)...)
	}
	return errs
}

// propPositionsCoverInput asserts that concatenating the raw text of all leaf
// nodes covers the entire input (with correct ordering).
func TestProperty_PositionsCoverInput(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genFullJSONC(t)
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		reconstructed := doc.RawText()
		if len(reconstructed) != len(input) {
			t.Fatalf("RawText length %d != input length %d\ninput: %q\nraw:  %q",
				len(reconstructed), len(input), input, reconstructed)
		}
		if reconstructed != input {
			t.Fatalf("RawText doesn't match input\ninput: %q\nraw:   %q", input, reconstructed)
		}
	})
}

// ============================================================================
// SECTION 5: Serialization round-trip properties
// ============================================================================

// propSerializeIdentity asserts parse → serialize returns identical text (for
// inputs without disallowed tokens).
func TestProperty_SerializeIdentity(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genJSONWithoutComments.Draw(t, "jsonInput")
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		output := Serialize(doc)
		if output != input {
			// Allow for edge cases: normalized numbers etc.
			// For now, check via re-parse
			doc2, err2 := Parse([]byte(output))
			if err2 != nil {
				t.Fatalf("Serialize output doesn't re-parse: %v\ninput: %q\noutput: %q", err2, input, output)
			}
			if !doc.DeepEqual(doc2) {
				t.Fatalf("Serialize output produces different CST\ninput: %q\noutput: %q", input, output)
			}
		}
	})
}

// propParseSerializeIdempotent asserts parse(serialize(parse(x))) == parse(x)
func TestProperty_ParseSerializeIdempotent(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genFullJSONC(t)
		doc1, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		serialized := Serialize(doc1)
		doc2, err := Parse([]byte(serialized))
		if err != nil {
			t.Fatalf("Re-parse error: %v\nserialized: %q", err, serialized)
		}
		if !doc1.DeepEqual(doc2) {
			t.Fatalf("Not idempotent\ninput: %q\nserialized: %q\ndoc1: %s\ndoc2: %s",
				input, serialized, doc1, doc2)
		}
	})
}

// ============================================================================
// SECTION 6: Formatting properties
// ============================================================================

// propFormatPreservesSemantics asserts that after formatting, the semantic
// values (strings, numbers, booleans, nulls) remain unchanged.
func TestProperty_FormatPreservesSemantics(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genFullJSONC(t)
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		formatted := Format(doc, &FormatOptions{Indent: "  "})
		doc2, err := Parse([]byte(formatted))
		if err != nil {
			t.Fatalf("Format output doesn't re-parse: %v\nformatted: %q", err, formatted)
		}
		// Check structural equivalence (same values, ignore whitespace)
		if !semanticDeepEqual(doc, doc2) {
			t.Fatalf("Format changed semantics\ninput: %q\nformatted: %q", input, formatted)
		}
	})
}

// propFormatWithDifferentIndent asserts various indent styles work.
func TestProperty_FormatWithDifferentIndent(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genFullJSONC(t)
		indent := rapid.SampledFrom([]string{"  ", "    ", "\t", ""}).Draw(t, "indent")
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		formatted := Format(doc, &FormatOptions{Indent: indent})
		doc2, err := Parse([]byte(formatted))
		if err != nil {
			t.Fatalf("Format with indent %q failed re-parse: %v\nformatted: %q",
				indent, err, formatted)
		}
		if !semanticDeepEqual(doc, doc2) {
			t.Fatalf("Format with indent %q changed semantics", indent)
		}
	})
}

// propFormatReIndentIdempotent asserts format(format(x)) == format(x)
func TestProperty_FormatReIndentIdempotent(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genFullJSONC(t)
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		f1 := Format(doc, &FormatOptions{Indent: "  "})
		doc2, err := Parse([]byte(f1))
		if err != nil {
			t.Fatalf("First format re-parse error: %v", err)
		}
		f2 := Format(doc2, &FormatOptions{Indent: "  "})
		if f1 != f2 {
			t.Fatalf("Format not idempotent\nfirst:  %q\nsecond: %q", f1, f2)
		}
	})
}

// ============================================================================
// SECTION 7: Error handling properties
// ============================================================================

// propRejectTruncatedInput asserts that incomplete input generates an error node.
func TestProperty_RejectTruncatedInput(t *testing.T) {
	tests := []string{
		`{"a": `,
		`"hello`,
	}
	for _, tc := range tests {
		t.Run(tc, func(t *testing.T) {
			doc, err := Parse([]byte(tc))
			if err == nil {
				errs := doc.FindAll(KindError)
				if len(errs) == 0 {
					t.Fatalf("Expected error nodes for truncated input %q", tc)
				}
			}
		})
	}
}

// propRejectInvalidJSON asserts certain invalid inputs return error.
func TestProperty_RejectInvalidJSON(t *testing.T) {
	tests := []string{
		`{a: 1}`,       // unquoted key
		`{'a': 1}`,     // single quote
		`[true false]`, // missing comma
		`[1,,2]`,       // double comma
		`{`,            // unterminated object
		`[`,            // unterminated array
		`01`,           // leading zero (non-zero prefixed)
		`-01`,          // leading zero negative
		`truee`,        // unknown keyword
		`nul`,          // truncated keyword
		"\x00[1]",      // null byte
	}
	for _, tc := range tests {
		t.Run("", func(t *testing.T) {
			doc, err := Parse([]byte(tc))
			if err == nil && doc == nil {
				t.Fatalf("Expected error or non-nil doc for %q", tc)
			}
		})
	}
}

// ============================================================================
// SECTION 8: Edge cases and Unicode
// ============================================================================

// propParseEmptyArray asserts empty arrays work.
func TestProperty_ParseEmptyArray(t *testing.T) {
	doc, err := Parse([]byte("[]"))
	if err != nil {
		t.Fatalf("Parse error for empty array: %v", err)
	}
	arr := doc.FirstChild()
	if arr == nil || arr.Kind != KindArray {
		t.Fatalf("Expected Array, got %v", arr)
	}
	elements := arr.Elements()
	if len(elements) != 0 {
		t.Fatalf("Expected 0 elements, got %d", len(elements))
	}
}

// propParseEmptyObject asserts empty objects work.
func TestProperty_ParseEmptyObject(t *testing.T) {
	doc, err := Parse([]byte("{}"))
	if err != nil {
		t.Fatalf("Parse error for empty object: %v", err)
	}
	obj := doc.FirstChild()
	if obj == nil || obj.Kind != KindObject {
		t.Fatalf("Expected Object, got %v", obj)
	}
	members := obj.Members()
	if len(members) != 0 {
		t.Fatalf("Expected 0 members, got %d", len(members))
	}
}

// propParseVariousWhitespace asserts various whitespace formats work.
func TestProperty_ParseVariousWhitespace(t *testing.T) {
	inputs := []string{
		"[1]",
		"  [1]",
		"[1]  ",
		"\n\t[1]\r\n",
		"  \n  [1]  \t  ",
		"[  1  ]",
	}
	for _, input := range inputs {
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error for %q: %v", input, err)
		}
		// Must have an array with element 1
		arr := doc.FirstChild()
		if arr == nil || arr.Kind != KindArray {
			t.Fatalf("Expected Array for %q", input)
		}
	}
}

// propParseUnicodeStrings asserts strings with Unicode are preserved.
func TestProperty_ParseUnicodeStrings(t *testing.T) {
	src := `["hello αβγ world 🚀"]`
	doc, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse error for unicode string: %v", err)
	}
	strs := doc.FindAll(KindString)
	if len(strs) == 0 {
		t.Fatal("No String nodes found")
	}
	for _, s := range strs {
		if s.Value == "" {
			continue
		}
		// Verify the value is well-formed
		if !utf8.ValidString(s.Value) {
			t.Fatalf("String value contains invalid UTF-8: %q", s.Value)
		}
	}
}

// propParseEscapeSequences asserts common escape sequences work.
func TestProperty_ParseEscapeSequences(t *testing.T) {
	tests := []string{
		`["hello\nworld"]`,                   // newline escape
		`["hello\tworld"]`,                   // tab escape
		`["hello\"world"]`,                   // quote escape
		`["hello\\world"]`,                   // backslash escape
		`["hello\/world"]`,                   // slash escape
		`["hello\bworld"]`,                   // backspace
		`["hello\fworld"]`,                   // form feed
		`["hello\rworld"]`,                   // carriage return
		`["\u0048\u0065\u006C\u006C\u006F"]`, // unicode escapes: "Hello"
		`["\u00E9"]`,                         // é
		`["\u2603"]`,                         // ☃ snowman
		`["\u0000"]`,                         // null byte
	}
	for _, src := range tests {
		t.Run("", func(t *testing.T) {
			doc, err := Parse([]byte(src))
			if err != nil {
				t.Fatalf("Parse error for %q: %v", src, err)
			}
			strs := doc.FindAll(KindString)
			if len(strs) == 0 {
				t.Fatalf("No String nodes for %q", src)
			}
		})
	}
}

// ============================================================================
// SECTION 9: Deep / complex inputs
// ============================================================================

// propParseLargeNesting asserts deeply nested structures handle recursion well.
func TestProperty_ParseLargeNesting(t *testing.T) {
	// Build a deeply nested array: [[[[...]]]]
	var sb strings.Builder
	depth := 50
	for i := 0; i < depth; i++ {
		sb.WriteString("[")
	}
	sb.WriteString("1")
	for i := 0; i < depth; i++ {
		sb.WriteString("]")
	}
	src := sb.String()
	doc, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse error for deep nesting: %v", err)
	}
	// Walk to verify depth
	current := doc
	actualDepth := 0
	for _, c := range current.Children {
		if c.Kind == KindArray {
			_ = c
			actualDepth++
		}
	}
	// We may not get full depth if we don't recurse enough, but shouldn't crash
	_ = actualDepth
}

// propParseComplexGeneratedJSON asserts the generator itself is valid.
func TestProperty_ParseComplexGeneratedJSON(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		// Generate multiple times and combine
		var parts []string
		n := rapid.IntRange(0, 3).Draw(t, "n")
		for i := 0; i < n; i++ {
			parts = append(parts, genFullJSONC(t))
		}
		// Wrap as an array to make it valid (multiple top-level values aren't valid JSON)
		src := "[" + strings.Join(parts, ",") + "]"
		doc, err := Parse([]byte(src))
		if err != nil {
			t.Fatalf("Parse error for combined JSONC: %v\ninput: %q", err, src)
		}
		if doc == nil {
			t.Fatal("Nil document returned")
		}
	})
}

// ============================================================================
// HELPER: Semantic deep compare (ignores trivia)
// ============================================================================

// semanticDeepEqual compares two CST trees ignoring whitespace and comment nodes.
// Returns true if they have the same value structure.
func semanticDeepEqual(a, b *Node) bool {
	if a == nil && b == nil {
		return true
	}
	if a == nil || b == nil {
		return false
	}

	// For leaf value nodes: compare kind and value
	if !a.IsContainer() && !b.IsContainer() {
		if a.IsTrivia() && b.IsTrivia() {
			return true // ignore trivia
		}
		if a.IsTrivia() || b.IsTrivia() {
			return false
		}
		return a.Kind == b.Kind && a.Value == b.Value
	}

	// Container nodes: filter trivia, compare children pairwise
	aKids := filterNonTriviaCST(a.Children)
	bKids := filterNonTriviaCST(b.Children)

	if len(aKids) != len(bKids) {
		return false
	}
	if a.Kind != b.Kind {
		return false
	}
	for i := range aKids {
		if !semanticDeepEqual(aKids[i], bKids[i]) {
			return false
		}
	}
	return true
}

// ============================================================================
// SECTION 10: XML/JSON compatible edge cases
// ============================================================================

// propParseTrailingComma asserts JSONC permits trailing commas.
func TestProperty_ParseTrailingComma(t *testing.T) {
	tests := []string{
		`[1, 2, 3,]`,
		`{"a": 1, "b": 2,}`,
		`[1,]`,
		`{"a": 1,}`,
	}
	for _, src := range tests {
		t.Run("", func(t *testing.T) {
			doc, err := Parse([]byte(src))
			if err != nil {
				t.Fatalf("Parse error for trailing comma %q: %v", src, err)
			}
			if doc == nil {
				t.Fatal("Nil document")
			}
		})
	}
}

// ============================================================================
// SECTION 11: Whitespace preservation
// ============================================================================

// propWhitespacePreserved asserts that whitespace nodes are present.
func TestProperty_WhitespacePreserved(t *testing.T) {
	src := "  [  1  ]  "
	doc, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse error: %v", err)
	}
	// Check there are whitespace nodes
	ws := doc.FindAll(KindWhitespace)
	if len(ws) == 0 {
		t.Fatalf("Expected whitespace nodes for %q", src)
	}
}

// ============================================================================
// SECTION 12: Error nodes and recovery
// ============================================================================

// propErrorNodeForInvalid asserts that invalid JSON creates error nodes.
func TestProperty_ErrorNodeForInvalid(t *testing.T) {
	tests := []struct {
		input string
		msg   string
	}{
		{`{"a": 01}`, "leading zero in number"},
		{`{"a": true false}`, "extra tokens"},
		{`{`, "unterminated"},
		{`[1,`, "unterminated array"},
	}
	for _, tc := range tests {
		t.Run(tc.msg, func(t *testing.T) {
			doc, err := Parse([]byte(tc.input))
			if err == nil {
				// Should have error nodes
				errs := doc.FindAll(KindError)
				if len(errs) == 0 {
					t.Logf("No error nodes for %q (may still be valid parse strategy)", tc.input)
				}
			}
		})
	}
}

// TestPropertyIntegrity runs a rapid check over all integration-level properties.
func TestProperty_MustRoundTrip(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genFullJSONC(t)
		doc, err := Parse([]byte(input))
		if err != nil {
			return // skip inputs that genuinely can't parse
		}
		// Round-trip through serialize
		serialized := Serialize(doc)
		doc2, err2 := Parse([]byte(serialized))
		if err2 != nil {
			t.Fatalf("Round-trip broke: %v\ninput: %q\nserialized: %q", err2, input, serialized)
		}
		// Structural equality (including trivia)
		if !doc.DeepEqual(doc2) {
			// Debug: show what's different
			t.Fatalf("Round-trip changed structure\ninput: %q\nserialized: %q", input, serialized)
		}
	})
}

// TestProperty_CanonicalNumberFormat verifies that certain number formats
// parse and re-serialize consistently.
func TestProperty_CanonicalNumberFormat(t *testing.T) {
	tests := []string{
		`[0]`,
		`[-0]`,
		`[1]`,
		`[-1]`,
		`[1.5]`,
		`[1.0]`,  // explicit .0
		`[-2.0]`, // negative with .0
		`[1e10]`,
		`[1E10]`, // uppercase E
		`[1e+5]`, // explicit + in exponent
		`[1e-3]`,
		`[1.5e-3]`,
		`[1.2345678901234567e+308]`,
	}
	for _, src := range tests {
		t.Run(src, func(t *testing.T) {
			doc, err := Parse([]byte(src))
			if err != nil {
				t.Fatalf("Parse error for %q: %v", src, err)
			}
			nums := doc.FindAll(KindNumber)
			if len(nums) == 0 {
				t.Fatalf("No number nodes for %q", src)
			}
		})
	}
}

// ============================================================================
// SECTION 11: Additional coverage for previously uncovered cases
// ============================================================================

// propFormatReIndentAllIndents asserts format(format(x, INDENT)) == format(x, INDENT)
// for multiple indent strings, not just the default "  ".
func TestProperty_FormatReIndentAllIndents(t *testing.T) {
	indents := []string{"  ", "    ", "\t", ""}
	rapid.Check(t, func(t *rapid.T) {
		input := genFullJSONC(t)
		indent := rapid.SampledFrom(indents).Draw(t, "indent")
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		f1 := Format(doc, &FormatOptions{Indent: indent})
		doc2, err := Parse([]byte(f1))
		if err != nil {
			t.Fatalf("First format re-parse error with indent %q: %v\nformatted: %q",
				indent, err, f1)
		}
		f2 := Format(doc2, &FormatOptions{Indent: indent})
		if f1 != f2 {
			t.Fatalf("Format not idempotent with indent %q\ninput: %q\nfirst:  %q\nsecond: %q",
				indent, input, f1, f2)
		}
	})
}

// propFormatSerializeStability asserts that Format(Serialize(doc)) == Format(doc)
// for a property-generated document — the cross-function round-trip is stable.
func TestProperty_FormatSerializeStability(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		input := genFullJSONC(t)
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error: %v", err)
		}
		// Serialize drops all trivia (whitespace, comments).
		s := Serialize(doc)
		docS, err := Parse([]byte(s))
		if err != nil {
			t.Fatalf("Serialize output doesn't re-parse: %v\nserialized: %q", err, s)
		}
		// Format both.
		f1 := Format(doc, &FormatOptions{Indent: "  "})
		f2 := Format(docS, &FormatOptions{Indent: "  "})
		// They must be structurally equivalent (same values, same layout).
		if f1 != f2 {
			t.Fatalf("Format(Serialize(doc)) != Format(doc)"+
				"\n  doc Format:  %q\n  ser Format:  %q\n  input: %q\n  serialized: %q",
				f1, f2, input, s)
		}
	})
}

// propDeepNesting500 asserts the parser handles at least 500 levels of nesting
// for both objects and arrays (covers stack safety).
func TestProperty_DeepNesting500(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		depth := rapid.IntRange(500, 600).Draw(t, "depth")
		var sb strings.Builder
		sb.WriteString(genTrivia(t))
		// Deeply nested arrays: [[[[...]]]]
		for i := 0; i < depth; i++ {
			sb.WriteString("[")
		}
		sb.WriteString(genValue(t))
		for i := 0; i < depth; i++ {
			sb.WriteString("]")
		}
		sb.WriteString(genTrivia(t))
		input := sb.String()
		doc, err := Parse([]byte(input))
		if err != nil {
			t.Fatalf("Parse error at depth %d: %v", depth, err)
		}
		// Verify formatting round-trips
		f1 := Format(doc, &FormatOptions{Indent: "  "})
		doc2, err := Parse([]byte(f1))
		if err != nil {
			t.Fatalf("Format re-parse error at depth %d: %v\nformatted (truncated): %.100q",
				depth, err, f1)
		}
		f2 := Format(doc2, &FormatOptions{Indent: "  "})
		if f1 != f2 {
			t.Fatalf("Format not idempotent at depth %d\nfirst (truncated): %.100q\nsecond (truncated): %.100q", depth, f1, f2)
		}
	})
}
